server:
  port: 8001
spring:
  application:
    name: cloud-payment-service

  datasource:
    #当前数据源操作类型
    type: com.alibaba.druid.pool.DruidDataSource
    #mysql驱动包
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/blackHole?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: lbd123

  #P94 需要的配置
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 1  #采样率值介于0-1之间,1标识全部采集

mybatis:
  mapperLocations: classpath:mapper/*.xml
  #所有entity别名类所在包
  type-aliases-package: com.alaili.springcloud.entities